-------------------------------\
-----------FUNCTIONS-----------|
-------------------------------/

CREATE FUNCTION [dbo].[f_SHOWCUSTOMERSOLDERTHAN] (@YEARS INT)
RETURNS TABLE
AS
	RETURN
		SELECT DISTINCT SLB.CUSTOMERSID, C.FIRSTNAME, C.LASTNAME, [LATEST VISIT] 
			FROM v_SHOWCUSTOMERSLATESTBOOKINGS SLB
			INNER JOIN BOOKINGS B ON SLB.CUSTOMERSID = B.CUSTOMERSID
			INNER JOIN CUSTOMERS C ON C.ID=SLB.CUSTOMERSID
			WHERE [LATEST VISIT] < DATEADD(YEAR, -@YEARS, GETDATE())