--EN TRIGGER SOM RÄKNAR UT TOTALKOSTNADEN FÖR EN BOKNING

--DEN BEHÖVER KUNDENS ID, KUNDTYP, ANTAL RUM, ANTAL DAGAR, VILKA RUM OCH OM DET FINNS EXTRA SÄNG

--FÖRST SKAPA EN VIEW MED INFO VI BEHÖVER
CREATE VIEW [dbo].[v_SHOWPAYMENTINFO] AS
	SELECT B.CUSTOMERSID, C.CUSTOMERTYPESID, C.FIRSTNAME, C.LASTNAME, B.ID AS BOOKINGSID, DATEDIFF(day, STARTDATE, ENDDATE) AS TOTALDAYS, RT.NAME AS ROOMNAME, RT.COST AS ROOMCOST, B.EXTRABED, CT.[DISCOUNTPERCENT]
		FROM CUSTOMERS C
		INNER JOIN BOOKINGS B ON B.CUSTOMERSID=C.ID
		INNER JOIN BOOKINGSROOMS BR ON BR.BOOKINGSID=B.ID
		INNER JOIN ROOMS R ON R.ID=BR.ROOMSID
		INNER JOIN ROOMTYPES RT ON RT.ID=R.ROOMTYPESID
		INNER JOIN CUSTOMERTYPES CT ON CT.ID=C.CUSTOMERTYPESID