---------------------------\
-----------VIEWS-----------|
---------------------------/

--KOLLAR ALLA KUNDERS SENASTE BOKNINGAR OCH VISAR DE BOKNINGAR SOM ÄR ÄLDRE ÄN 2 ÅR
CREATE VIEW [dbo].[v_SHOWCUSTOMERSLATESTBOOKINGS] AS
	SELECT B.CUSTOMERSID, MAX(B.STARTDATE) AS [LATEST VISIT]
		FROM BOOKINGS B
		GROUP BY B.CUSTOMERSID