------------------------------------------------------------\
------------------------------------------------------------/

--KOLLAR IGENOM ALLA KUNDER SOM ÄR GAMLA OCH OM DE INTE ÄR REDAN ÄNDRADE TILL '--DELETED--'
CREATE VIEW [dbo].[v_SHOWCUSTOMERSTODELETE]
AS
	SELECT SCOT.CUSTOMERSID, SCOT.[LATEST VISIT], C.FIRSTNAME, C.LASTNAME
		FROM f_SHOWCUSTOMERSOLDERTHAN(2) SCOT
		INNER JOIN CUSTOMERS C ON C.ID = SCOT.CUSTOMERSID
		WHERE C.FIRSTNAME NOT IN ('--DELETED--')