--SKAPAR EN BOKNING ALLT UTOM TIMEDEPARTURE SOM OCKSÅ TAR RUMSNUMMER SP OCH SAMTIDIGT GÖR EN INSERT INTO BOOKINGSROOMS

CREATE PROCEDURE [dbo].[sp_BOOKINGS_INSERT] 
@CUSTOMERSID INT,
@QTYPERSONS INT,
@STARTDATE DATE,
@ENDDATE DATE,
@ETA DATETIME,
@TIMEARRIVAL DATETIME,
@SPECIALNEEDS TEXT,
@EXTRABED BIT,
@PARKING BIT,
@BREAKFAST BIT,
@STAFFID INT,
@ROOMID INT
AS

BEGIN TRY
    BEGIN TRANSACTION 
		
		IF @ENDDATE >= @STARTDATE
			BEGIN
				INSERT INTO BOOKINGS (QTYPERSONS, STARTDATE, ENDDATE, ETA, TIMEARRIVAL, SPECIALNEEDS, EXTRABED, PARKING, BREAKFAST, CUSTOMERSID, STAFFID)
					VALUES (@QTYPERSONS, @STARTDATE, @ENDDATE, @ETA, @TIMEARRIVAL, @SPECIALNEEDS, @EXTRABED, @PARKING, @BREAKFAST, @CUSTOMERSID, @STAFFID);
		
					DECLARE @BOOKID INT
					SELECT @BOOKID = ID
					FROM BOOKINGS
					WHERE ID = (SELECT TOP(1) ID FROM BOOKINGS ORDER BY ID DESC)

					INSERT INTO BOOKINGSROOMS
					VALUES(@BOOKID, @ROOMID)
					COMMIT
			END
		ELSE
			BEGIN
				PRINT 'END DATE CAN NOT BE EARLIER THAN START DATE!'
			END
	END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK
END CATCH