--PROCEDURE SOM SKAPAR EN TRANSACTION TOKEN
CREATE PROCEDURE [dbo].[sp_CHECK_IN_TRANSACTION_TOKEN] @CUSTID INT, @BOOKID INT AS

	--GÖR EN INSERT INTO PAYMENTS NÄR EN BOKNING SKAPAS
	--DÅ KAN DEN FÅ EN TRANSACTIONTOKEN SOM TRIGGER

	DECLARE @TRANSTOKEN BIGINT
	SET @TRANSTOKEN = ABS(CHECKSUM(NEWID()) % (99999999 - 10000000 + 1)) + 10000000

	--GÖR OM TILL UPDATE

	INSERT INTO PAYMENTS(CUSTOMERSID, TRANSACTIONTOKEN, BOOKINGSID)
	VALUES(@CUSTID, @TRANSTOKEN, @BOOKID)