--EN LOOP
CREATE PROCEDURE [dbo].[sp_DELETE_OLD_CUSTOMERS_SENSITIVE_INFORMATION] AS

	DECLARE @CUSTID INT

	DECLARE CUSTIDCURSOR CURSOR
	FOR
		SELECT CUSTOMERSID
		FROM v_SHOWCUSTOMERSTODELETE
		ORDER BY CUSTOMERSID

	OPEN CUSTIDCURSOR
		FETCH NEXT FROM CUSTIDCURSOR INTO @CUSTID

	WHILE @@FETCH_STATUS = 0
		BEGIN

			EXEC sp_CHANGE_SENSITIVE_INFO_TO '--DELETED--', @CUSTID

			FETCH NEXT FROM CUSTIDCURSOR INTO @CUSTID
		END

	CLOSE CUSTIDCURSOR
	DEALLOCATE CUSTIDCURSOR