------------------------------------------------------------\
------------------------------------------------------------/

--VI MÅSTE FÅ TAG PÅ ALLA BOKNINGAR SOM DEN HÄR KUNDEN HAR GJORT
--LOOPAR IGENOM EN FUNCTION SOM VISAR EN KUNDS ALLA BOKNINGAR MED HJÄLP AV KUNDID

CREATE PROCEDURE [dbo].[sp_DELETE_CUSTOMERS_BOOKINGS] @CUSTID INT
AS
--KOLLAR IGENOM ALLA BOKNINGAR FÖR ATT SE OM KUNDEN FINNS I NÅGRA ANDRA BOKNINGAR
	DECLARE @BOOKID INT

	DECLARE BOOKIDCURSOR CURSOR
	FOR
		SELECT ID
		--EN FUNCTION SOM VISAR ALLA KUNDENS BOKNINGAR
		FROM f_SHOWCUSTOMERSBOOKINGS(@CUSTID) SCB
		ORDER BY SCB.ID

		OPEN BOOKIDCURSOR
			FETCH NEXT FROM BOOKIDCURSOR INTO @BOOKID

--EN LOOP SOM KOLLAR AV BOKNINGSID FRÅN FUNCTION OCH TAR BORT ALLA BOKNINGAR, BOOKINGSROOMS OCH RECENSIONER

			WHILE @@FETCH_STATUS = 0
				BEGIN

					EXEC sp_DELETE_REVIEW_PROCEDURE @BOOKID
					EXEC sp_DELETE_BOOKINGSROOMS_PROCEDURE @BOOKID
					EXEC sp_DELETE_BOOKINGS_PROCEDURE @BOOKID

					FETCH NEXT FROM BOOKIDCURSOR INTO @BOOKID
				END

	CLOSE BOOKIDCURSOR
		DEALLOCATE BOOKIDCURSOR