CREATE TABLE [dbo].[ACCOUNTS] (
    [ID]           INT          IDENTITY (1, 1) NOT NULL,
    [USERNAME]     VARCHAR (50) NOT NULL,
    [USERPASSWORD] VARCHAR (50) NOT NULL,
    [CUSTOMERSID]  BIGINT       NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([CUSTOMERSID]) REFERENCES [dbo].[CUSTOMERS] ([ID])
);

