CREATE TABLE [dbo].[BOOKINGSROOMS] (
    [BOOKINGSID] BIGINT   NOT NULL,
    [ROOMSID]    SMALLINT NOT NULL,
    CONSTRAINT [PK_BOOKINGSROOMS] PRIMARY KEY CLUSTERED ([BOOKINGSID] ASC, [ROOMSID] ASC),
    CONSTRAINT [FK_BOOKINGS_RUM_ROOMS] FOREIGN KEY ([ROOMSID]) REFERENCES [dbo].[ROOMS] ([ID]),
    CONSTRAINT [FK_BOOKINGS_RUMSBOKNI_BOOKINGS] FOREIGN KEY ([BOOKINGSID]) REFERENCES [dbo].[BOOKINGS] ([ID])
);

