CREATE TABLE [dbo].[CUSTOMERTYPES] (
    [ID]              SMALLINT     IDENTITY (1, 1) NOT NULL,
    [TYPENAME]        VARCHAR (30) NULL,
    [DISCOUNTPERCENT] DECIMAL (18) NULL,
    CONSTRAINT [PK_CUSTOMERTYPES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

