CREATE TABLE [dbo].[CUSTOMERS] (
    [ID]              BIGINT       IDENTITY (1, 1) NOT NULL,
    [SOCNUMBER]       VARCHAR (13) NOT NULL,
    [FIRSTNAME]       VARCHAR (30) NOT NULL,
    [LASTNAME]        VARCHAR (30) NOT NULL,
    [EMAIL]           VARCHAR (60) NOT NULL,
    [STREETADRESS]    VARCHAR (60) NOT NULL,
    [CITY]            VARCHAR (30) NOT NULL,
    [COUNTRY]         VARCHAR (30) NOT NULL,
    [ICE]             VARCHAR (60) NULL,
    [CUSTOMERTYPESID] SMALLINT     NOT NULL,
    CONSTRAINT [PK_CUSTOMERS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CUSTOMER_KUNDTYPER_CUSTOMER] FOREIGN KEY ([CUSTOMERTYPESID]) REFERENCES [dbo].[CUSTOMERTYPES] ([ID])
);

