CREATE TABLE [dbo].[PAYMENTS] (
    [ID]               BIGINT       IDENTITY (1, 1) NOT NULL,
    [TOTALCOST]        MONEY        NULL,
    [TRANSACTIONTOKEN] VARCHAR (50) NOT NULL,
    [BOOKINGSID]       BIGINT       NULL,
    [DISCOUNTMONEY]    INT          NULL,
    [CUSTOMERSID]      BIGINT       NOT NULL,
    CONSTRAINT [PK_PAYMENTS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PAYMENTS_BETALNING_CUSTOMER] FOREIGN KEY ([CUSTOMERSID]) REFERENCES [dbo].[CUSTOMERS] ([ID])
);

