CREATE TABLE [dbo].[PHONENUMBERS] (
    [ID]                 BIGINT       IDENTITY (1, 1) NOT NULL,
    [PHONENUMBER]        VARCHAR (20) NULL,
    [CUSTOMERSID]        BIGINT       NOT NULL,
    [PHONENUMBERTYPESID] SMALLINT     NOT NULL,
    CONSTRAINT [PK_PHONENUMBERS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PHONENUM_NUMMERTYP_PHONENUM] FOREIGN KEY ([PHONENUMBERTYPESID]) REFERENCES [dbo].[PHONENUMBERTYPES] ([ID]),
    CONSTRAINT [FK_PHONENUM_TELEFONNU_CUSTOMER] FOREIGN KEY ([CUSTOMERSID]) REFERENCES [dbo].[CUSTOMERS] ([ID])
);

