CREATE TABLE [dbo].[PHONENUMBERTYPES] (
    [ID]       SMALLINT     IDENTITY (1, 1) NOT NULL,
    [TYPENAME] VARCHAR (10) NOT NULL,
    CONSTRAINT [PK_PHONENUMBERTYPES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

