CREATE TABLE [dbo].[REVIEWS] (
    [ID]             INT      IDENTITY (1, 1) NOT NULL,
    [CUSTOMERSID]    BIGINT   NOT NULL,
    [RATING]         SMALLINT NOT NULL,
    [CUSTOMERREVIEW] TEXT     NULL,
    [BOOKINGSID]     BIGINT   NOT NULL,
    CONSTRAINT [PK_REVIEWS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_REVIEWS_RECENSION_BOOKINGS] FOREIGN KEY ([BOOKINGSID]) REFERENCES [dbo].[BOOKINGS] ([ID])
);


GO
--TRIGGER SOM KOLLAR SÅ ATT MAN BARA KAN LÄGGA IN EN RATING MELLAN 1 OCH 5
CREATE TRIGGER [dbo].[tr_CHECK_REVIEW_RATING]
ON [dbo].[REVIEWS]
FOR INSERT
AS
	IF EXISTS(
		SELECT * FROM INSERTED
		WHERE RATING < 1 OR RATING > 5)

		BEGIN
			PRINT 'RATING HAS TO BE BETWEEN 1 AND 5
			'
			ROLLBACK
		END