CREATE TABLE [dbo].[ROOMTYPES] (
    [ID]      SMALLINT     IDENTITY (1, 1) NOT NULL,
    [NAME]    VARCHAR (40) NOT NULL,
    [COST]    MONEY        NOT NULL,
    [QTYBEDS] SMALLINT     NOT NULL,
    CONSTRAINT [PK_ROOMTYPES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

