CREATE TABLE [dbo].[ROOMS] (
    [ID]          SMALLINT IDENTITY (1, 1) NOT NULL,
    [ROOMNUM]     SMALLINT NOT NULL,
    [ROOMTYPESID] SMALLINT NOT NULL,
    CONSTRAINT [PK_ROOMS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ROOMS_ROOMSROOM_ROOMTYPE] FOREIGN KEY ([ROOMTYPESID]) REFERENCES [dbo].[ROOMTYPES] ([ID])
);

