CREATE TABLE [dbo].[STAFF] (
    [ID]            INT          IDENTITY (1, 1) NOT NULL,
    [FIRSTNAME]     VARCHAR (30) NOT NULL,
    [LASTNAME]      VARCHAR (30) NOT NULL,
    [PHONENUMBER]   VARCHAR (30) NOT NULL,
    [EMAIL]         VARCHAR (30) NOT NULL,
    [DEPARTMENTSID] SMALLINT     NOT NULL,
    CONSTRAINT [PK_STAFF] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_STAFF_AVDELNING_DEPARTME] FOREIGN KEY ([DEPARTMENTSID]) REFERENCES [dbo].[DEPARTMENTS] ([ID])
);

